### ISSUE TITLE
Are the mobile and desktop apps (including the productivity suite) going to be released as open source?

### ISSUE THREAD

**Issue by 3699n** [skiff-org/skiff-mail#10]

**Comment by rolltidehero** [comment]
Doesn't seem like it.

**Comment by amilich** [comment]
Hey! @3699n @rolltidehero the codebase is actually shared across all products.

**Comment by rolltidehero** [comment]
> Hey! @3699n @rolltidehero the codebase is actually shared across all products.

Oh okay. Are the other Skiff projects open-source too? Good job!

**Comment by rolltidehero** [comment]
> Hey! @3699n @rolltidehero the codebase is actually shared across all products.

Are 

> Pages &  Drive

 open-source as well? 

That would be a cool trio to self-host, fork and contribute.

**Comment by amilich** [comment]
> > Hey! @3699n @rolltidehero the codebase is actually shared across all products.
> 
> Are
> 
> > Pages &  Drive
> 
> open-source as well?
> 
> That would be a cool trio to self-host, fork and contribute.

The entire product codebase for Pages/Drive isn't yet, but most of the building blocks are - our encryption library, our UI library, and a lot of the shared code with Skiff Mail is also used in Pages/Drive

**Comment by rolltidehero** [comment]
Cool. I'm following :)
