### ISSUE TITLE
Integrate `Drive` in the top-left menu — currently `Mail` and `Pages`

### ISSUE THREAD

**Issue by x80486** [skiff-org/skiff-mail#14]

**Comment by jgdevelopment** [comment]
For feature requests like this I recommend sending an email to support@skiff.com or using the in-app feedback modal. Issues should be related to code-specific changes.

Note: this feature is already in development.

**Comment by x80486** [comment]
I see this was (just) released.

**Comment by amilich** [comment]
Yep :)
