### ISSUE TITLE
Control over stored/sent e-mail addresses

### ISSUE THREAD

**Issue by x80486** [skiff-org/skiff-mail#17]
Looks like every time an e-mail is sent, the address is stored automatically — hopefully encrypted as well within the account.

Would be great to have control over those, sort of like a traditional address book or a similar solution.

**Comment by amilich** [comment]
Great idea, lots of requests for address books/contact info. Any notes or other contact details would be E2EE.

**Comment by x80486** [comment]
I know you are busy with other things, but do you have any plans to implement something similar to an `Address Book`? It's a little bit weird now; when I decide to compose an e-mail I see addresses I've received and some of the ones I've sent, but there it's not entirely clear.
