### ISSUE TITLE
Open source license

### ISSUE THREAD

**Issue by shazow** [skiff-org/skiff-mail#2]
Hiya. :) I was just reading through the code, and I noticed that the landing page promotes that the project is open source, but the only [license in the repo is a Creative Commons license](https://github.com/skiff-org/skiff-mail/blob/8d234a110fce02804665d1f305cb2893f5dcd61e/LICENSE). Perhaps it's an oversight but I wanted to note that CC licenses are designed for media rather than code, and there's a lot of edge cases that make it risky to treat CC code as open source (especially regarding protections for the authors, contributors, and users).

Would be a good idea to choose one of the OSI-approved licenses: https://opensource.org/licenses

This will help limit liabilities for everyone involved, and increase likelihood of collaboration/adoption. :)

Apache2 is a safe and uncontroversial choice. If you want to go maximally permissive (optimize for third-party usage and contributors, my usual preference) then MIT and BSD are great. If you want something more restrictive, then LGPL/GPL/MPL are worth looking at.

Hope this is helpful! Feel free to close if it's not an oversight.

**Comment by amilich** [comment]
Thank you for the feedback! I will share it with our open source legal team. There are definitely reasons why we currently go with CC, largely around non-commercial use. Please email me (hello@) if you have more questions on this too.

**Comment by adulau** [comment]
I would then recommend to avoid the term open source in your communication and website. It’s not following the OSI guidelines. And it’s kind of misleading for the potential users. Thank you.
