### ISSUE TITLE
Session Management

### ISSUE THREAD

**Issue by x80486** [skiff-org/skiff-mail#22]
This is a useful feature to allow users to visualize and manage _active sessions_. Could be really handy to display in what device it's being used.

**Comment by amilich** [comment]
This is a great idea. Will close for now because we can't put it on the roadmap yet, but it's a very cool idea.

**Comment by x80486** [comment]
Yeah, but why close it? It's more useful to track these things here until they are done. I'm not entirely sure how are you doing the project management, but so far, for the "outside world", the GitHub issues is the only way to provide feedback.

**Comment by amilich** [comment]
We do add the issues to our internal tracker, which now is on https://linear.app/ (doesn't have a public facing option yet, but we'd love to have that).
