### ISSUE TITLE
Error "Unable to load page" for Inbox messages on Android

### ISSUE THREAD

**Issue by sumeetadur** [skiff-org/skiff-mail#27]
The following error page is shown when I go to an Inbox message on the Android app. Pressing the Reload button leads to a blank screen, and pressing the phone's back button doesn't have any effect. The only way to get back to the main screen is to swipe the app out from the recent apps list (or to force stop) and start the app again. If I want to see a message on my phone, I can only use the web version.

![Screenshot_20221227-010533__01](https://user-images.githubusercontent.com/15633037/209595761-a034478c-e0bd-4990-a4f0-55ad8c989059.jpg)

**Comment by amilich** [comment]
Do you have any information on the type of email (or if it is a marketing email we can view)? Can you check this on the web?

**Comment by sumeetadur** [comment]
@amilich it seems to be emails that contain images. Here's an example from the web app:
![Screenshot_20230104-112008__01](https://user-images.githubusercontent.com/15633037/210544475-c72c0680-2c2c-46c9-ad35-1400bbe0787e.jpg)

**Comment by sumeetadur** [comment]
@amilich I'm not sure what's changed, but this seems to be fixed now
