### ISSUE TITLE
the ability for the user to opt out of this

### ISSUE THREAD

**Issue by Wjxfi** [skiff-org/skiff-mail#32]
![308087.jpg](https://user-images.githubusercontent.com/113500363/215313992-1c9ceb47-0aae-4a43-a52b-b9b021061b9c.jpg)

**Comment by amilich** [comment]
We don’t use these analytics. Please check a post on our Reddit.

**Comment by amilich** [comment]
This report does not mean they are used. They may be included in a sub dependency. But we do not use them and no data is sent to them.

**Comment by amilich** [comment]
Sure, but they are unused and do not send or receive any data or network requests, so it is not particularly high on our priority list. This would be an informational level report.
